In [19]:
import tensorflow as tf
print(tf.__version__)

2.13.1


In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
sent=[  'the book on the table',
     'Bring the glass of milk ',
     'He goes to the market everyday',
    'Meena claims the property',
     'is she fine?',
     'lets go to the zoo',
     'you cook really amazing']

In [22]:
sent


['the book on the table',
 'Bring the glass of milk ',
 'He goes to the market everyday',
 'Meena claims the property',
 'is she fine?',
 'lets go to the zoo',
 'you cook really amazing']

In [23]:
voc_size = 400

In [24]:
onehot_repr=[one_hot(words,voc_size)for words in sent]

In [25]:
print(onehot_repr)

[[72, 117, 197, 72, 176], [179, 72, 247, 45, 176], [248, 21, 351, 72, 301, 298], [57, 108, 72, 8], [162, 109, 359], [334, 34, 351, 72, 95], [334, 192, 356, 189]]


In [26]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential 

In [27]:
import numpy as np

In [28]:
sent_length = 10
embedded_docs=pad_sequences(onehot_repr, padding = 'pre',maxlen = sent_length)
print(embedded_docs)

[[  0   0   0   0   0  72 117 197  72 176]
 [  0   0   0   0   0 179  72 247  45 176]
 [  0   0   0   0 248  21 351  72 301 298]
 [  0   0   0   0   0   0  57 108  72   8]
 [  0   0   0   0   0   0   0 162 109 359]
 [  0   0   0   0   0 334  34 351  72  95]
 [  0   0   0   0   0   0 334 192 356 189]]


In [29]:
model = Sequential()
model.add(Embedding(voc_size , 7 , input_length=sent_length))
model.compile('adam' , 'mse')

In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 7)             2800      
                                                                 
Total params: 2800 (10.94 KB)
Trainable params: 2800 (10.94 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
embedded_docs[0]

array([  0,   0,   0,   0,   0,  72, 117, 197,  72, 176])

In [32]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 58ms/step


array([[-0.01562705, -0.01612213,  0.01654091,  0.04113818,  0.04047674,
        -0.04938601,  0.0103564 ],
       [-0.01562705, -0.01612213,  0.01654091,  0.04113818,  0.04047674,
        -0.04938601,  0.0103564 ],
       [-0.01562705, -0.01612213,  0.01654091,  0.04113818,  0.04047674,
        -0.04938601,  0.0103564 ],
       [-0.01562705, -0.01612213,  0.01654091,  0.04113818,  0.04047674,
        -0.04938601,  0.0103564 ],
       [-0.01562705, -0.01612213,  0.01654091,  0.04113818,  0.04047674,
        -0.04938601,  0.0103564 ],
       [ 0.00801184, -0.02034267, -0.01357306,  0.0125595 , -0.03829545,
        -0.03803247,  0.01266626],
       [-0.02565721,  0.04787589,  0.01941374,  0.04345896, -0.04277903,
        -0.02214551, -0.01583755],
       [-0.0350632 ,  0.00521071, -0.04558743,  0.00764791, -0.01328193,
         0.00767148, -0.04222948],
       [ 0.00801184, -0.02034267, -0.01357306,  0.0125595 , -0.03829545,
        -0.03803247,  0.01266626],
       [ 0.04355286, -0.0071

In [33]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 63ms/step
[[[-0.01562705 -0.01612213  0.01654091  0.04113818  0.04047674
   -0.04938601  0.0103564 ]
  [-0.01562705 -0.01612213  0.01654091  0.04113818  0.04047674
   -0.04938601  0.0103564 ]
  [-0.01562705 -0.01612213  0.01654091  0.04113818  0.04047674
   -0.04938601  0.0103564 ]
  [-0.01562705 -0.01612213  0.01654091  0.04113818  0.04047674
   -0.04938601  0.0103564 ]
  [-0.01562705 -0.01612213  0.01654091  0.04113818  0.04047674
   -0.04938601  0.0103564 ]
  [ 0.00801184 -0.02034267 -0.01357306  0.0125595  -0.03829545
   -0.03803247  0.01266626]
  [-0.02565721  0.04787589  0.01941374  0.04345896 -0.04277903
   -0.02214551 -0.01583755]
  [-0.0350632   0.00521071 -0.04558743  0.00764791 -0.01328193
    0.00767148 -0.04222948]
  [ 0.00801184 -0.02034267 -0.01357306  0.0125595  -0.03829545
   -0.03803247  0.01266626]
  [ 0.04355286 -0.00712381  0.0028468  -0.04790256  0.04525678
   -0.01924378  0.00395108]]

 [[-0.01562705 -0.01612213  0.016540

In [34]:
!pip install nltk


  Using cached nltk-3.8.1-py3-none-any.whl.metadata (2.8 kB)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
